package br.com.wsintegrabolao.entity;
// Generated 25/03/2018 00:53:08 by Hibernate Tools 3.6.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Equipe generated by hbm2java
 */
@Entity
@Table(name = "equipe", schema = "public"
)
public class Equipe implements java.io.Serializable {

    @Id
    @Column(name = "cd_equipe", nullable = false, length = 10)
    private String cdEquipe;
    @Column(name = "br_equipe", length = 100)
    private String brEquipe;
    @Column(name = "cor_equipe", length = 100)
    private String corEquipe;
    @Column(name = "nm_equipe", length = 100)
    private String nmEquipe;
    @Column(name = "nm_comum", length = 100)
    private String nmComum;
    @Column(name = "nm_slug", length = 100)
    private String nmSlug;
    @Column(name = "sg_equipe", length = 10)
    private String sgEquipe;
    @Column(name = "tg_equipe", length = 100)
    private String tgEquipe;
    @Column(name = "tp_equipe", length = 100)
    private String tpEquipe;
    @Column(name = "uri_equipe", length = 100)
    private String uriEquipe;

    public Equipe() {
    }

    public Equipe(String cdEquipe) {
        this.cdEquipe = cdEquipe;
    }

    public Equipe(String cdEquipe, String brEquipe, String corEquipe, String nmEquipe, String nmComum, String nmSlug, String sgEquipe, String tgEquipe, String tpEquipe, String uriEquipe) {
        this.cdEquipe = cdEquipe;
        this.brEquipe = brEquipe;
        this.corEquipe = corEquipe;
        this.nmEquipe = nmEquipe;
        this.nmComum = nmComum;
        this.nmSlug = nmSlug;
        this.sgEquipe = sgEquipe;
        this.tgEquipe = tgEquipe;
        this.tpEquipe = tpEquipe;
        this.uriEquipe = uriEquipe;
    }

    public String getCdEquipe() {
        return this.cdEquipe;
    }

    public void setCdEquipe(String cdEquipe) {
        this.cdEquipe = cdEquipe;
    }

    public String getBrEquipe() {
        return this.brEquipe;
    }

    public void setBrEquipe(String brEquipe) {
        this.brEquipe = brEquipe;
    }

    public String getCorEquipe() {
        return this.corEquipe;
    }

    public void setCorEquipe(String corEquipe) {
        this.corEquipe = corEquipe;
    }

    public String getNmEquipe() {
        return this.nmEquipe;
    }

    public void setNmEquipe(String nmEquipe) {
        this.nmEquipe = nmEquipe;
    }

    public String getNmComum() {
        return this.nmComum;
    }

    public void setNmComum(String nmComum) {
        this.nmComum = nmComum;
    }

    public String getNmSlug() {
        return this.nmSlug;
    }

    public void setNmSlug(String nmSlug) {
        this.nmSlug = nmSlug;
    }

    public String getSgEquipe() {
        return this.sgEquipe;
    }

    public void setSgEquipe(String sgEquipe) {
        this.sgEquipe = sgEquipe;
    }

    public String getTgEquipe() {
        return this.tgEquipe;
    }

    public void setTgEquipe(String tgEquipe) {
        this.tgEquipe = tgEquipe;
    }

    public String getTpEquipe() {
        return this.tpEquipe;
    }

    public void setTpEquipe(String tpEquipe) {
        this.tpEquipe = tpEquipe;
    }

    public String getUriEquipe() {
        return this.uriEquipe;
    }

    public void setUriEquipe(String uriEquipe) {
        this.uriEquipe = uriEquipe;
    }

}
