package br.com.wsintegrabolao.entity;
// Generated 25/03/2018 00:53:08 by Hibernate Tools 3.6.0

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TipousuarioDAO generated by hbm2java
 */
@Entity
@Table(name = "tipousuario", schema = "public"
)
@JsonIgnoreProperties ({ "hibernateLazyInitializer" , "handler" })
public class TipousuarioDAO implements java.io.Serializable {

    private int cdTipo;
    private String dsTipo;

    public TipousuarioDAO() {
    }

    public TipousuarioDAO(int cdTipo, String dsTipo) {
        this.cdTipo = cdTipo;
        this.dsTipo = dsTipo;
    }

    public TipousuarioDAO(int cdTipo, String dsTipo, Set usuarios) {
        this.cdTipo = cdTipo;
        this.dsTipo = dsTipo;
    }    
    
    @Id
    @Column(name = "cd_tipo", nullable = false)
    public int getCdTipo() {
        return this.cdTipo;
    }

    public void setCdTipo(int cdTipo) {
        this.cdTipo = cdTipo;
    }

    @Column(name = "ds_tipo", nullable = false, length = 60)
    public String getDsTipo() {
        return this.dsTipo;
    }

    public void setDsTipo(String dsTipo) {
        this.dsTipo = dsTipo;
    }

}
